### ISSUE TITLE
Cannot find module testcontainers-node-playwright'

### ISSUE THREAD

**Issue by mareru** [javierlopezdeancos/testcontainers-node-playwright#14]
I get this error in the line `import { PlaywrightContainer } from 'testcontainers-node-playwright';`:
`Cannot find module 'testcontainers-node-playwright' or its corresponding type declarations`

I did `npm install testcontainers-node-playwright --save-dev`
All went through without any errors but the file cannot recognize that the module is installed.

I am using Windows 10 Pro on a VM
Node v20.16.0
npm 10.5.2
I didn't install Docker yet on the VM - is this necessary for the import to be recognized? I don't think so, right?
Thanks in advance for the help

**Comment by javierlopezdeancos** [comment]
Hi, you are right, its not necessary install docker in order to have a well import recognized experience in the typescript code so, I will try to take a look a it.

**Comment by javierlopezdeancos** [comment]
Hi @mareru 
this new release https://github.com/javierlopezdeancos/testcontainers-node-playwright/releases/tag/0.5.2  fix the problem
<img width="1459" alt="Captura de pantalla 2024-08-21 a las 0 16 42" src="https://github.com/user-attachments/assets/9ec2a3a0-99d3-49f5-b349-fe99945d4c71">

I don't know when the publish process remove the build step 🤷🏻‍♂️

**Comment by javierlopezdeancos** [comment]
Close the issue.

**Comment by mareru** [comment]
Thanks, I will try it out. Just out of curiosity, what was the issue, can you explain in a few sentences? I see there is no PR that was merged in order to fix it, or I am not looking correctly :)

**Comment by javierlopezdeancos** [comment]
I don't know when the publishing action deletes the build step. In this commit https://github.com/javierlopezdeancos/testcontainers-node-playwright/commit/64cc8fe1afbe285ba96bc159793e181f4c90bbdd, sorry but I fix directly on master, I group again all publishing action with:

```
install dependencies
pass linter
pass tests
build
```

Now, this last step build, create the build folder with all needed files to be packaged and published right.
